# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0744072af67bfbfd902bbf3165c441a799ead8731689d6a3b1badc19ca085518ba88af10847639cb65978ba0b65b4e8925c2f0709d405c04953dadb416b1fdd2

test:
  secret_key_base: 6ecfcf3b825994b160fbb97e5942f78dd2d88bc604905486818ad6fab3233454ff3e59717f0ad80c720cdda664f6ad99ae649899bb3edb1d2ff40e41d53aae6e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
